### ISSUE TITLE
Some question about the dataset

### ISSUE THREAD

**Issue by Alex-LI-1996** [JWFangit/LOTVS-DADA#2]
Hi, Professor Fang. Can you release the data on the original information of the fixation points?

**Comment by Cogito2012** [comment]
I agree with @Alex-LI-1996 , it could be more valuable to provide original eye-tracking data, i.e., fixation points with timestamps. We sincerely hope this data can also be released.

**Comment by YanDingXin** [comment]
> Hi, Professor Fang. Can you release the data on the original information of the fixation points?

Hello, it's nice to have your attention.The ground truth of our data set have been adjusted and will be uploaded as soon as possible, as well as releasing the raw data from the eye tracker and the code for our maps how to generate.We are dealing with this matter, please be patient...

**Comment by YanDingXin** [comment]
> Hi, Professor Fang. Can you release the data on the original information of the fixation points?

Our data set has been uploaded again. You can download it now. Thank you for your attention.

**Comment by Alex-LI-1996** [comment]
When will you update the data in the paper？

**Comment by YanDingXin** [comment]
> When will you update the data in the paper？

Now we upload the part of the dat set used in this paper, about half of which. The other part will be uploaded soon.

**Comment by Alex-LI-1996** [comment]
![image](https://user-images.githubusercontent.com/63184678/89140550-82774a80-d574-11ea-9d42-c7e34d129934.png)
When will you update the data in this table？

**Comment by Alex-LI-1996** [comment]
![image](https://user-images.githubusercontent.com/63184678/89140652-cb2f0380-d574-11ea-97e6-f4baa78604b4.png)
![image](https://user-images.githubusercontent.com/63184678/89140674-dbdf7980-d574-11ea-8f43-2d6b19baadc2.png)

I noticed that the method of generating truth values is different and I want to know whether the data in the following table should be updated?

![image](https://user-images.githubusercontent.com/63184678/89140769-3973c600-d575-11ea-86dd-2ed569000bed.png)

**Comment by YanDingXin** [comment]
Since the real value of our maps has changed, all the experiments have been done again, and the data in this table has also changed.  The picture you showed is an old dataset, which is the version we uploaded before.The  focus map is not generated by Gaussian, and our paper has already answered these questions when replying to the review comments. The new data set will be used later.

**Comment by Alex-LI-1996** [comment]
thank you

**Comment by Cogito2012** [comment]
@YanDingXin Could you please make it clear which part of the ground truth has been changed? For example, the number of annotated frames, the values of saliency maps, and the accident windows of each video, I am wondering if and how these are updated. Thanks!

**Comment by YanDingXin** [comment]
> @YanDingXin Could you please make it clear which part of the ground truth has been changed? For example, the number of annotated frames, the values of saliency maps, and the accident windows of each video, I am wondering if and how these are updated. Thanks!

Thank you for your attention. Our dat set changes only focus map. in the previous version, focus map is an image exported by eye tracker. in the new version, we generate focus map through fixation points. if you don't use foucus map, you don't need to update it. if you use focus map, it is recommended to download it again. (I think the new dataset is more convenient to use)

**Comment by Cogito2012** [comment]
> > @YanDingXin Could you please make it clear which part of the ground truth has been changed? For example, the number of annotated frames, the values of saliency maps, and the accident windows of each video, I am wondering if and how these are updated. Thanks!
> 
> Thank you for your attention. Our dat set changes only focus map. in the previous version, focus map is an image exported by eye tracker. in the new version, we generate focus map through fixation points. if you don't use foucus map, you don't need to update it. if you use focus map, it is recommended to download it again. (I think the new dataset is more convenient to use)

Thanks for your reply, I am clear now. By the way, I noticed that the dataset structure is also different, but there is no clear introduction to the content of json files. It would be great if you can attach a README file to explain json content.

**Comment by Alex-LI-1996** [comment]
The generation of focus map is similar to the DR (eye) VE?

**Comment by YanDingXin** [comment]
> The generation of focus map is similar to the DR (eye) VE?

It should be different. The way we generate focus map is similar to this one. [DHF1K](https://github.com/wenguanwang/DHF1K/issues/2)

**Comment by YanDingXin** [comment]
> > > @YanDingXin Could you please make it clear which part of the ground truth has been changed? For example, the number of annotated frames, the values of saliency maps, and the accident windows of each video, I am wondering if and how these are updated. Thanks!
> > 
> > 
> > Thank you for your attention. Our dat set changes only focus map. in the previous version, focus map is an image exported by eye tracker. in the new version, we generate focus map through fixation points. if you don't use foucus map, you don't need to update it. if you use focus map, it is recommended to download it again. (I think the new dataset is more convenient to use)
> 
> Thanks for your reply, I am clear now. By the way, I noticed that the dataset structure is also different, but there is no clear introduction to the content of json files. It would be great if you can attach a README file to explain json content.

Thank you for pointing out this problem. We will update README soon to explain the function of json content.
